### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by Drangonliao123** [DLUT-yyc/Isomer#2]
When I run the code(./scripts/infer.sh) for validation, the code reports the following error:
Traceback (most recent call last):
  File "tools/inference.py", line 9, in <module>
    from lib.builder import VOSNet
  File "/mnt/d/Project/Isomer/tools/../lib/__init__.py", line 3, in <module>       
    from .module import *
  File "/mnt/d/Project/Isomer/tools/../lib/module/__init__.py", line 3, in <module>
    from .cst import ContextSharingTransformer
  File "/mnt/d/Project/Isomer/tools/../lib/module/cst.py", line 7, in <module>     
    from mmcv.cnn import constant_init, kaiming_init
ImportError: cannot import name 'constant_init' from 'mmcv.cnn' (/home/liao/anaconda3/envs/lsomer/lib/python3.8/site-packages/mmcv/cnn/__init__.py)

Can you please tell me what the problem is?

**Comment by DLUT-yyc** [comment]
This seems to be a problem with [MMCV](https://github.com/open-mmlab/mmcv). You can ask MMCV for help.

Good luck!

**Comment by DLUT-yyc** [comment]
This seems to be a problem with [MMCV](https://github.com/open-mmlab/mmcv). You can ask MMCV for help.

Good luck!

**Comment by umarjibrilmohd** [comment]
please, what's the use of the password, because i downloaded the model without any password

**Comment by umarjibrilmohd** [comment]
but i cant run the infer.sh

**Comment by DLUT-yyc** [comment]
> please, what's the use of the password, because i downloaded the model without any password

I initially uploaded the model to the network disk (password required for access), and later transferred the model to huggingface (no password required for access) for more convenient downloading. So you can access it now without a password. I have updated the readme file. Thank you for the reminder.

**Comment by DLUT-yyc** [comment]
> but i cant run the infer.sh

You can describe in detail the problems you encounter so that I can help you solve them.
